spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tmsgo_db  # 사용하려는 DB 이름 (변경 가능)
    username: root  # MariaDB 사용자명
    password: 1234  # MariaDB 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update  # 자동 테이블 생성 및 업데이트 추후 none으로 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server.port: 8088