
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tmsgo_db  # ✅ MariaDB 접속 정보
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update  # (create, update, validate, none 설정 가능 운영시 validate, none사용)
  show-sql: true
  properties:
    hibernate:
      format_sql: true

server.port: 8088

